### ISSUE TITLE
Add multiselection by mouse down + drag to select everything in the rectangle

### ISSUE THREAD

**Issue by 3ti65** [BF3RM/MapEditor#58]
This: 

https://i.imgur.com/1359OaZ.png

should lead to this:

https://i.imgur.com/V6qey9v.png

It's supposed to select all the buildings within that rectangle and put it into the multiselection. Selection has to also be represented in the hierarchy tree.

**Comment by Raikem** [comment]
This might help
https://github.com/mrdoob/three.js/issues/1826

**Comment by 3ti65** [comment]
Your editor sucks lol

**Comment by Powback** [comment]
TODO: Hire someone to do this

**Comment by Raikem** [comment]
It shouldn't be too hard, we can make it so it only selects custom objects

**Comment by Powback** [comment]
Added in latest build

**Comment by FoolHen** [comment]
Broke multiselection unselecting.

**Comment by Powback** [comment]
Adding other issue for multiselection.
